import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import FirebaseProvider from "@/components/providers/FirebaseProvider";
import { ThemeProvider } from "@/components/providers/ThemeProvider";

const workSans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={workSans.className}>
        <FirebaseProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
            {children}
          </ThemeProvider>
        </FirebaseProvider>
      </body>
    </html>
  );
}
