import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import Providers from "@/components/providers";
import "./globals.css";

const workSans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={workSans.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
